### ISSUE TITLE
TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by ghost** [Iskawo/Rada#13]
Hello, So i just used this source code and i set up everything right, but i get this error every time i create a channel/delete a channel delete a message etc.

`TypeError: Cannot read property 'url' of undefined`

anyone know how i fix it?

**Comment by bizojs** [comment]
sorry about that. it's due to the custom emote used in the embed for logging. you can fix this by removing the code to grab the custom emote or change it to a different emote.

**Comment by ghost** [comment]
Works now thanks!
