### ISSUE TITLE
Where can I change the emojis config?

### ISSUE THREAD

**Issue by nForce6791** [Iskawo/Rada#14]
In many files it'll say something like `${emotes.success}` but how can i get to changing the success emoji and whatever? I've searched everywhere, unless I'm blind.

**Comment by brys0** [comment]
Hi, first off you're viewing the old repository please use the new one (https://github.com/RadaBot/Rada)
Secondly, you can change the emoji bindings in https://github.com/RadaBot/Rada/blob/master/lib/util/constants.js

In the future we'll definitely be thinking about adding config for this. Thanks for the heads up!

**Comment by brys0** [comment]
Let me know if that fixes your issue!

**Comment by nForce6791** [comment]
Thank you. I know I'm on the old repo but I'd prefer v12 over v13 for now. Appreciate the help!

**Comment by brys0** [comment]
Alright! That shouldn't be a problem; However, I'm not sure of the state for this older repo, and stability. You can get those exact emojis from the Discord server if that interests you. Otherwise just use your own.
